apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-service
  labels:
    name: business-service
spec:
  replicas: 2
  selector:
    matchLabels:
      name: business-service
  template:
    metadata:
      labels:
        name: business-service
    spec:
      containers:
      - name: business-service
        image: swwwt/business-service
        command: ["dotnet"]
        args: ["business-service.dll"]
        ports:
        - containerPort: 80
        
---

kind: Service
apiVersion: v1
metadata:
  name: restful-api
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: business-service